name: build and release beta version
on:
  push:
    branches: [beta]

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6'
      
      - name: Build with Xcode
        run: |
          xcodebuild clean build \
            -project Micmute.xcodeproj \
            -scheme Micmute \
            -configuration Debug \
            -destination "platform=macOS" \
            -derivedDataPath build_output

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: Micmute
          path: ./build_output/Build/Products/Release/Micmute.app

      - name: Show Build Logs if Failed 
        if: ${{ failure() }}
        run: |
          cat build_output/Logs/Build/*.log
