name: build and release beta version
on:
  push:
    branches: [beta]

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Build with Xcode
        run: |
          xcodebuild clean build \
            -project Micmute.xcodeproj \
            -scheme Micmute \
            -configuration Debug \
            -destination "platform=macOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath build_output

      - name: Archive artifact
        run: |
          cd ./build_output/Build/Products/Debug
          ditto -c -k --sequesterRsrc --keepParent Micmute.app Micmute-Beta.zip
          mv Micmute-Beta.zip $GITHUB_WORKSPACE/Micmute-Beta.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Micmute-Beta.zip
          path: ${{ github.workspace }}/Micmute-Beta.zip

  release:
    needs: build
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Micmute-Beta.zip
          path: .

      - name: Generate commit list
        id: commit_list
        shell: bash
        run: |
          commit_list_output=$(echo "${{ toJson(github.event) }}" | jq -r '.commits[] | "- [\(.id)](\(.url)) - \(.author.name)"')
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$commit_list_output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release (Beta)
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v3.0.0-beta.${{ github.run_number }}"
          name: "Micmute 3.0.0 Beta (${{ github.run_number }})"
          body: |
              **Commits**
              ${{ steps.commit_list.outputs.commits }}
          prerelease: true
          draft: false
          files: Micmute-Beta.zip
