name: build and release beta version
on:
  push:
    branches: [beta]

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Build with Xcode
        run: |
          xcodebuild clean build \
            -project Micmute.xcodeproj \
            -scheme Micmute \
            -configuration Debug \
            -destination "platform=macOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath build_output

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: MicmuteBeta
          path: ./build_output/Build/Products/Debug/Micmute.app

  release:
    needs: build
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MicmuteBeta

      - name: Zip application
        run: |
          ditto -c -k --sequesterRsrc --keepParent "Micmute.app" "Micmute-Beta.zip"
    
      - name: Create GitHub Release (Beta)
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v3.0.0-beta.${{ github.run_number }}"
          name: "Micmute 3.0.0 Beta (${{ github.run_number }})"
          body: "Beta build from commit: ${{ github.sha }}"
          prerelease: true
          draft: false
          files: |
            Micmute-Beta.zip
