name: build and release beta version
on:
  push:
    branches: [beta]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["6.0.2"]
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6'
      - name: Setup Swift
        run: swift --version

      - name: Build with Xcode
        run: |
          xcodebuild -project Micmute.xcodeproj -scheme Micmute -configuration Release -derivedDataPath build_output

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: Micmute
          path: ./build_output/Build/Products/Release/Micmute.app
