name: build and release beta version
on:
  push:
    branches: [beta]

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Build with Xcode
        run: |
          xcodebuild clean build \
            -project Micmute.xcodeproj \
            -scheme Micmute \
            -configuration Debug \
            -destination "platform=macOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath build_output

      - name: Archive artifact
        run: |
          cd ./build_output/Build/Products/Debug
          ditto -c -k --sequesterRsrc --keepParent Micmute.app Micmute-Beta.zip
          mv Micmute-Beta.zip $GITHUB_WORKSPACE/Micmute-Beta.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Micmute-Beta.zip
          path: ${{ github.workspace }}/Micmute-Beta.zip

  release:
    needs: build
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Micmute-Beta.zip
          path: .


      - name: Create release
        uses: marvinpinto/action-automatic-releases@master
        with:
          files: Micmute-Beta.zip
          automatic_release_tag: 'v3.0.0-beta.${{ github.run_number }}'
          title: 'Micmute 3.0.0 Beta (${{ github.run_number }})'
          draft: false
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
