name: Build and release
on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: macos-15
    outputs:
      app_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0'

      - name: Determine app version
        id: get_version
        run: |
          set -eo pipefail
          version=$(xcodebuild -project Micmute.xcodeproj -scheme Micmute -configuration Release -showBuildSettings | awk '/MARKETING_VERSION/ {print $3; exit}')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE: ${{ secrets.SIGNING_CERTIFICATE }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          security create-keychain -p temporary_password build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p temporary_password build.keychain

          echo "$SIGNING_CERTIFICATE" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$SIGNING_PASSWORD" -T /usr/bin/codesign

          security set-key-partition-list -S apple-tool:,apple: -s -k temporary_password build.keychain

          security find-identity -v -p codesigning build.keychain

      - name: Build with Xcode
        run: |
          xcodebuild clean build \
            -project Micmute.xcodeproj \
            -scheme Micmute \
            -configuration Release \
            -destination "platform=macOS" \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath build_output

      - name: Archive artifact
        run: |
          cd ./build_output/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent Micmute.app Micmute.zip
          mv Micmute.zip $GITHUB_WORKSPACE/Micmute.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Micmute.zip
          path: ${{ github.workspace }}/Micmute.zip

  release:
    needs: build
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Micmute.zip
          path: .

      - name: Create release
        uses: marvinpinto/action-automatic-releases@master
        with:
          files: Micmute.zip
          automatic_release_tag: ${{ needs.build.outputs.app_version }}
          title: "v${{ needs.build.outputs.app_version }}"
          draft: false
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
