name: Build and release

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: fwal/setup-swift@v2
        with:
          swift-version: '6.1'

      - name: Install CocoaPods
        run: |
          brew install cocoapods || true

      - name: Build with Xcode
        run: |
          xcodebuild clean build \
            -project Micmute.xcodeproj \
            -scheme Micmute \
            -configuration Release \
            -destination "platform=macOS,arch=arm64" \
            -derivedDataPath build_output \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_ENTITLEMENTS=""

      - name: Archive artifact
        run: |
          cd ./build_output/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent Micmute.app Micmute-${{ steps.get_version.outputs.version }}.zip
          mv Micmute-${{ steps.get_version.outputs.version }}.zip $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Micmute-${{ steps.get_version.outputs.version }}
          path: ${{ github.workspace }}/Micmute-${{ steps.get_version.outputs.version }}.zip

  release:
    needs: build
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Micmute-${{ needs.build.outputs.app_version }}
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.app_version }}
          name: ${{ needs.build.outputs.app_version }}
          files: Micmute-${{ needs.build.outputs.app_version }}.zip
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
